### ISSUE TITLE
default/common missing after fresh build/install on CentOS 8.4

### ISSUE THREAD

**Issue by jwattyow** [daimh/sge#12]
I'm installing on a newly installed & configured CentOS 8.4. I've used the cmake commands and they worked fine, but I'm missing the default/common directory (and all its contents obviously). I've installed on other machines/VMs and it worked great, just not this one. Any idea what I missed? (Yes, I followed the instructions).

Thanks.
James.

**Comment by daimh** [comment]
Did you run the command below on your master node?

yes "" | ./install_qmaster


Best,
Manhong

**Comment by jwattyow** [comment]
I can't because I can't run 'source /opt/sge/default/common/settings.sh' because the default/common directory is missing. In my script, the install_qmaster command comes after sourcing the settings.

**Comment by daimh** [comment]
qmaster installation will create the folder.

Search 'production installation' in my repo readme.

Best,
Manhong

**Comment by jwattyow** [comment]
Thanks, that did it. I had that command after sourcing the setting.sh file.

James.

**Comment by daimh** [comment]
Thanks for the update!
