### ISSUE TITLE
Documentation for queue configuration?

### ISSUE THREAD

**Issue by jwattyow** [daimh/sge#13]
I'm trying to setup an execution host independent of the admin host. The queues I've configured are showing up with 0 available cpus. Is there some documentation about how to properly setup/configure one admin host and several execution/submit hosts? I've been doing some web searches but haven't found anything helpful.

Thanks.
James.

**Comment by daimh** [comment]
You might want to use 'qconf -mq <QUEUE>' and then modify its slots.

http://www.softpanorama.org/HPC/Grid_engine/Queues/slots_attribute.shtml

**Comment by jwattyow** [comment]
Thanks for the above. I just did that on the admin host, created a new queue with the above command and modified the slots. Using qmon, the CQLOAD is still "NA" and AVAIL is still 0. The queue shows up in the 'cluster queue' tab on qmon. I'm not sure why the exec host isn't passing along the load values though. How do the load values get passed from the exec host to the admin host? Both daemons are running. The link you provided looks interesting and I'll be looking at it. Are you aware of any other sites that might have troubleshooting information?

Again, thanks very much for the help and the info, it's very helpful.

James.

**Comment by daimh** [comment]
If you copied the configuration 'default/ommon' from the master node to the exec node before running install_execd, the exec node should send its information to the master node, unless there is some firewall rules blocking it.

Can you run 'qhost -q' and 'iptables-save' on both master and exec node, please?

**Comment by jwattyow** [comment]
The results of qhost are the same on both machines (admin host and exec host).

bash-4.4$ qhost -q
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
build01                 -               -    -    -    -     -       -       -       -       -
   all.q                BIP   0/0/12        au
   build.q              BIP   0/0/10        au
grid-srv                lx-amd64       16    1    8   16  0.00   62.6G    2.7G   31.5G     0.0
   all.q                BIP   0/0/16       

When I run install_execd it says that the exec host is not an admin host. So I made it an admin host and was able to execute the install_execd script. The results were the same, however.

I was under the impression that all the queues would be on the admin host (grid-srv in this case), and that the execution hosts would just use those. This seems to be an incorrect assumption however. I'm still looking over the documentation to check this out.

Thanks.
James.

**Comment by daimh** [comment]
You guess is right. each execution host should has it own queue.

 I happened to release a video yesterday, which shows the 'qhost -q' output.

https://youtu.be/QNdIdodLJRY?list=PLcUreuc9RezIPip5ShBr3Wg1RrnrAv45X&t=21

**Comment by daimh** [comment]
Closed.

BTW, run make under  [five-stroke](https://github.com/daimh/sge/tree/master/5-keystrokes-to-setup-a-cluster-without-root-privilege) can create a demo cluster.
