### ISSUE TITLE
compiling failed on centos7.9

### ISSUE THREAD

**Issue by callesp** [daimh/sge#18]
Hi,
Thanks for your working on maintaining SGE. I've got an error while running `cmake --build build -j` on centos7.9, then i tried to change the version of gcc to 8.3.1, it's still there.

![image](https://user-images.githubusercontent.com/46679643/162471768-2d2a39ed-3028-41f3-ad45-a3bc61bbd54e.png)

Environments :
- os: centos7.9
- gcc: 8.3.1

I've tried to remove `static` keyword from the definition of function `bsd_signal` and it passed, could you help me figure out if this is nesscessary ?

**Comment by daimh** [comment]
Thanks a lot for opening this issue.

I retired qmake in commit a0a8024. qmake is based on an old version of gnu make. It is not a critical component of SGE.

While we can revisit this issue in future if needed, Here is a similar issue in 2011 just in case we have to compile qmake.
https://lists.gnu.org/archive/html/bug-make/2011-01/msg00028.html

**Comment by daimh** [comment]
Commit 39146a1 revived 'qmake' with two fixes.

One issue is the 'bsd_signal' error @callesp raised. The fix is to include signal.h in main.c.

The other issue is that qmake causes segfault in newer Linux. The fix is to set 'gl->gl_lstat'
