### ISSUE TITLE
berkeleydb/spoolinit undefined symbol:

### ISSUE THREAD

**Issue by aminasyan** [daimh/sge#19]
When using the spoolinit binary or using berkeleydb spooling method the libs/spool/berkeleydb/libspoolb.so library generates undefined symbol: error

Adding the following line in source/libs/spool/berkeleydb/CMakeLists.txt fixes it
target_link_libraries(spoolb db
)

**Comment by daimh** [comment]
Thanks a lot for opening this issue. fixed in a0a8024
