### ISSUE TITLE
qmon parallel environment configuration

### ISSUE THREAD

**Issue by whdxwym** [daimh/sge#20]
after I click the add/modify button, it will show segentation fault. I use centos 7.9

**Comment by daimh** [comment]
Thanks for reporting this issue!

While I will look into this when I get a chance, you might want to use 'qconf' instead, which always works.

**Comment by mperov** [comment]
Hello @whdxwym!
I use CentOS 7.9 too, but I have never faced segmentation fault when I run qmon...

**Comment by whdxwym** [comment]
> 

other functions are ok in qmon, it happens only I click add/modify button in parallel environment config.

**Comment by whdxwym** [comment]
> Hello @whdxwym! I use CentOS 7.9 too, but I have never faced segmentation fault when I run qmon... Could you attach backtrace?
> 
> Did you compile SGE from source how described [here](https://github.com/daimh/sge/blob/master/README.md)?
hello mperov, below is the info:

Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `qmon'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f7cd96bd481 in XtWidgetToApplicationContext ()
   from /lib64/libXt.so.6
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 expat-2.1.0-12.el7.x86_64 fontconfig-2.13.0-4.3.el7.x86_64 freetype-2.8-14.el7_9.1.x86_64 glibc-2.17-325.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-51.el7_9.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.7-4.el7_9.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXcursor-1.1.15-1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXfixes-5.0.3-1.el7.x86_64 libXft-2.3.2-2.el7.x86_64 libXmu-1.1.2-2.el7.x86_64 libXp-1.0.2-2.1.el7.x86_64 libXrender-0.9.10-1.el7.x86_64 libXt-1.1.5-3.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libjpeg-turbo-1.2.90-8.el7.x86_64 libpng-1.5.13-8.el7.x86_64 libselinux-2.5-15.el7.x86_64 libtirpc-0.2.4-0.16.el7.x86_64 libuuid-2.23.2-65.el7_9.1.x86_64 libxcb-1.13-1.el7.x86_64 motif-2.3.4-14.el7_5.x86_64 openssl-libs-1.0.2k-24.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64

**Comment by daimh** [comment]
I just pushed a new commit. Now 'qmon' works with the cmake installation too.

I also tested that 'qmon' doesn't have the segfault with either cmake or make installation. My test environment is the latest CentOS 7 with the additional "yum -y install xorg*".

Please test it and let us know how it goes. @whdxwym  

That being said, I haven't used 'qmon' for long time, as 'qconf' is easier, quicker, and always works with the minimal OS installation

**Comment by daimh** [comment]
Closed. Cannot Reproduce.
