### ISSUE TITLE
Execd exiting with status=5. What is status=5?

### ISSUE THREAD

**Issue by jwattyow** [daimh/sge#21]
I've installed the exec host software according to the docs, and have run the install_execd script. It runs, starts (according tot the logs), but then exits with status=5. I went looking through the code to see what's there (needs more comments), but couldn't find out what the meaning of the status indication is.

Is there a place to look to get that info? Can you say what the status is?

Thanks.
James.

**Comment by daimh** [comment]
Can you please add 'set -x' to the second line of inst_sge, and run ./install_execd again? It will tell us where the installation fails.

BTW, what Linux distribution and version are you using?

**Comment by jwattyow** [comment]
The install passed successfully, it's just that the execd daemon exits after. I tried updating some packages on one server and that seems to have solved one problem, but I'm seeing a 'status=1' failure on another server.

Another, perhaps related question, do I have to recompile on every server or can I simply copy the /opt/sge directory from the admin host to the execution and submit hosts? All the machines are the same and run the same OS/version.

Thanks for the help.

**Comment by daimh** [comment]
Glad to hear that it worked on one server. On the other failed one, can you try the installation from scratch? Under the 'tests' directory in my repo, you should be able to see my installation script specific for many popular Linux distributions. It might be helpful too.

In terms of your second question about copying /opt/sge. It will work if you are certain that all the machines have the same versions of packages, and you copy the files before running either 'install_qmaster' or 'install_execd'.

That being said, whenever in doubt, try removing everything under /opt/sge and compiling it on the node. It only takes a few seconds to re-compile everything with 'cmake -j' on a modern server.

**Comment by jwattyow** [comment]
Thanks for the reply. I re-did all the commands to build from scratch on the subject server. I then copied the default/common directory over from the admin host to the subject machine. 

The install_execd script ran to completion fine and even said the daemon started ok. The sgeexecd deamon then exits shortly after with status=1/FAILURE. I've also made sure all the devel packages were installed. Weird.

**Comment by daimh** [comment]
try 'systemctl disable sgeexecd' and 'systemctl stop sgeexecd', then add 'set -x' to the second line of /opt/sge/default/common/sgeexecd, then run '/opt/sge/default/common/sgeexecd', to see where it failed.

**Comment by jwattyow** [comment]
Thanks! Did that and got the following:

$ /opt/sge/default/common/sgeexecd
+ SGE_ROOT=/opt/sge
+ export SGE_ROOT
+ SGE_CELL=default
+ export SGE_CELL
+ unset SGE_QMASTER_PORT
+ unset SGE_EXECD_PORT
+ count=0
+ '[' '!' -d /opt/sge -a 0 -le 120 ']'
++ /opt/sge/util/arch
+ ARCH=lx-amd64
+ '[' -d /opt/sge/lib/lx-amd64 ']'
+ case $ARCH in
++ /opt/sge/util/arch -lib
+ shlib_path_name=LD_LIBRARY_PATH
++ eval echo '$LD_LIBRARY_PATH'
+++ echo
+ old_value=
+ '[' x = x ']'
+ eval LD_LIBRARY_PATH=/opt/sge/lib/lx-amd64
++ LD_LIBRARY_PATH=/opt/sge/lib/lx-amd64
+ export LD_LIBRARY_PATH
+ '[' -f /etc/default/sgeexecd ']'
+ '[' -f /etc/sysconfig/sgeexecd ']'
+ '[' 0 -gt 2 -o '' = -h -o '' = help ']'
+ startup=true
+ execd=true
+ softstop=false
+ stop=false
+ noSMF=false
+ status=false
++ GetPathToBinaries
++ cfgname=/opt/sge/default/common/bootstrap
++ base=none
++ '[' -f /opt/sge/default/common/bootstrap ']'
+++ grep binary_path /opt/sge/default/common/bootstrap
+++ awk '{ print $2 }'
++ base=/opt/sge/bin
++ '[' -f /opt/sge/bin/qstat ']'
++ '[' -f /opt/sge/util/arch ']'
+++ /opt/sge/util/arch
++ arch=lx-amd64
++ '[' -f /opt/sge/bin/lx-amd64/qstat ']'
++ base=/opt/sge/bin/lx-amd64
++ echo /opt/sge/bin/lx-amd64
+ bin_dir=/opt/sge/bin/lx-amd64
+ '[' /opt/sge/bin/lx-amd64 = none ']'
++ GetPathToUtilbin
++ base=none
++ '[' -f /opt/sge/util/arch ']'
++ utilbindir=/opt/sge/utilbin
+++ /opt/sge/util/arch
++ arch=lx-amd64
++ '[' -f /opt/sge/utilbin/lx-amd64/gethostname ']'
++ base=/opt/sge/utilbin/lx-amd64
++ echo /opt/sge/utilbin/lx-amd64
+ utilbin_dir=/opt/sge/utilbin/lx-amd64
+ '[' /opt/sge/utilbin/lx-amd64 = none ']'
++ /opt/sge/utilbin/lx-amd64/gethostname -aname
+ HOST=fpga-build01.rockport.lab
++ /opt/sge/utilbin/lx-amd64/gethostname -name
++ cut -f1 -d.
+ UQHOST=fpga-build01
++ GetExecdSpoolDir
+++ /opt/sge/bin/lx-amd64/qconf -sconf fpga-build01
+++ grep execd_spool_dir
+++ awk '{ print $2 }'
++ EXECD_SPOOL_DIR=
++ '[' '' = '' ']'
+++ /opt/sge/bin/lx-amd64/qconf -sconf
+++ grep execd_spool_dir
+++ awk '{ print $2 }'
++ EXECD_SPOOL_DIR=/opt/sge/default/spool
++ echo /opt/sge/default/spool
+ execd_run_dir=/opt/sge/default/spool/fpga-build01
+ DetectSMFService execd
+ name=execd
+ service=
+ '[' false = true ']'
+ '[' -f /lib/svc/share/smf_include.sh ']'
+ return
+ '[' false = true -o false = true ']'
+ '[' true = true ']'
+ /opt/sge/bin/lx-amd64/sge_shepherd -help
+ '[' '(' -z '' -o '' '!=' '' ')' -a -n '' ']'
+ '[' '' = '' ']'
++ /opt/sge/utilbin/lx-amd64/getservbyname -number sge-execd
+ ping_port=6445
+ echo '   Starting Grid Engine execution daemon'
   Starting Grid Engine execution daemon
+ exec
 
It looks like it started ok but it's not running now. Are there any debug args/params I can set or is there a place to modify the code to display a message with more details about why execd exits?

**Comment by daimh** [comment]
Unfortunately execd doesn't have such a running parameters to show more details.

What Linux distro and what installation method you are using? and which exit code (1 or 5) did you eventually get?

**Comment by jwattyow** [comment]
Sorry for the late reply, we've been out of power and internet for the last week. 

We're running CentOS 8.4 and I installed using cmake. The compile, build and install went through just fine, execd just doesn't stay running after the install_execd script executes.

I'm currently seeing execd end with status=1, which, if I'm reading the right source file, is a timeout. What's timing out?

I'll look at the tests directory now and post the results.

**Comment by daimh** [comment]
closed due to inactivity
