### ISSUE TITLE
Ubuntu 22.04 LTS: should libc.so.6 be executable?

### ISSUE THREAD

**Issue by Jerrythafast** [daimh/sge#22]
Hi! Thanks for keeping SGE alive and kickin'!

I have been trying to install this on Ubuntu 22.04 LTS (the official ISO from [here](https://ubuntu.com/download/server) which links me to [this](https://mirror.nl.leaseweb.net/ubuntu-releases/22.04/ubuntu-22.04-live-server-amd64.iso) mirror). It's a fresh install in VMware Workstation 16 Player.

Building and installation of qmaster went fine, but the systemd service is not starting. The problem is with `/opt/sge/util/arch`: this script assumes that `/lib/x86_64-linux-gnu/libc.so.6` is executable. I checked on some other server installs (Debian 9, Ubuntu 20.04.3, Debian 11) and it _was_ executable each time (`-rwxr-xr-x`). But on a fresh install of Ubuntu 22.04, it is not executable (`-rw-r--r--`)! Should I just make it executable manually, or is something else messing this up? According to the readme, you have successfully tested Ubuntu Server 22.04 on 2022-05-05. So I was wondering how you got around this problem? I looked but couldn't find the answer in the `tests` directory myself.

Thanks again,
Jerry

**Comment by daimh** [comment]
Hi Jerry,

  I believe a cmake installation doesn't check the execute bit, here is the output from the test VM built under 'tests/43231-ubuntu-22.04'.

root@ubuntu-22-04-sge:~# ps aux |grep sge
sge          965  0.2  0.3 771968  6948 ?        Sl   23:43   0:00 /opt/sge/bin/lx-amd64/sge_qmaster
sge         1059  0.1  0.2 221160  5836 ?        Sl   23:43   0:00 /opt/sge/bin/lx-amd64/sge_execd
root        1270  0.0  0.1   6476  2196 pts/0    S+   23:44   0:00 grep --color=auto sge
root@ubuntu-22-04-sge:~# ll /lib/x86_64-linux-gnu/libc.so.6 
-rw-r--r-- 1 root root 2216304 Mar  4 02:54 /lib/x86_64-linux-gnu/libc.so.6

  That being said, you can manually set the execute bit for the libc.so.6 to use the legacy installation method. This lib file can be executed to print version information.

Best,
Manhong

**Comment by Jerrythafast** [comment]
Hi Manhong,

Thanks for the quick response! I have tried it again and logged everything to be 100% sure. Turns out it *does* start successfully on this try (even with non-executable `libc.so.6`). Not sure why it didnt'work before.

However, I must note that SGE still attempts to run `libc.so.6` and produces "Permission denied" errors when it does. Also, two changes to `/etc/hosts` were required to get it to work:
1. The machine's hostname MUST be the first name listed after `127.0.0.1` (before `localhost`)
2. There must be a line with a non-`127.0.x.x` IP address and the machine's hostname


That said, here is my complete road to success-albeit-with-some-error-messages:

- Downloaded a fresh Ubuntu 22.04 iso, installed with default settings.
- Ran `sudo apt update && sudo apt full-upgrade`
- Rebooted for the sake of it
- Ran `sudo apt install -y git build-essential libhwloc-dev libssl-dev libtirpc-dev libmotif-dev libxext-dev libncurses-dev libdb5.3-dev libpam0g-dev pkgconf libsystemd-dev cmake`
- Rebooted again (why not)
- Saved the following script, which is a slightly modified copy of [tests/43231-ubuntu-22.04/lib/ubuntu-22.04.sh](https://github.com/daimh/sge/blob/dca6a39077e45a15cdf0199b015a08f32129acaa/tests/43231-ubuntu-22.04/lib/ubuntu-22.04.sh):
```bash
#!/usr/bin/env bash
set -ex 
sed -ie "s/127.0.0.1 localhost/127.0.0.1 `hostname` localhost\n`hostname -I` `hostname`/" /etc/hosts
git clone https://github.com/daimh/sge.git
cd sge
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/sge -DSYSTEMD=ON
cmake --build build -j
cmake --install build
useradd -r -d /opt/sge sge
chown -R sge /opt/sge
cd /opt/sge
yes "" | ./install_qmaster
source /opt/sge/default/common/settings.sh
qhost -q
qconf -as $HOSTNAME
```
- The changes are: removed the `apt` commands I already ran, added the `git clone` command, changed the `sed` command as explained above, uncommented the `useradd` command, removed the `./install_execd` command.
- Then I ran `sudo script.sh > stdout.txt 2> stderr.txt`
- And this is what I captured in `stderr.txt`:
```
++ hostname
++ hostname -I
++ hostname
+ sed -ie 's/127.0.0.1 localhost/127.0.0.1 ubumaster localhost\n192.168.116.134  ubumaster/' /etc/hosts
+ git clone https://github.com/daimh/sge.git
Cloning into 'sge'...
+ cd sge
+ cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/sge -DSYSTEMD=ON
+ cmake --build build -j
+ cmake --install build
+ useradd -r -d /opt/sge sge
+ chown -R sge /opt/sge
+ cd /opt/sge
+ yes ''
+ ./install_qmaster
util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
./util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
./util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
/opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
Created symlink /etc/systemd/system/multi-user.target.wants/sgemaster.service → /etc/systemd/system/sgemaster.service.
./util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
root@ubumaster added "@allhosts" to host group list
root@ubumaster added "all.q" to cluster queue list
changed scheduler configuration
+ source /opt/sge/default/common/settings.sh
++ SGE_ROOT=/opt/sge
++ export SGE_ROOT
++ '[' -x /opt/sge/util/arch ']'
+++ /opt/sge/util/arch
/opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
++ SGE_ARCH=lx-amd64
++ export SGE_ARCH
+++ /opt/sge/util/arch -m
/opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
++ DEFAULTMANPATH=/usr/share/man:/usr/local/share/man
+++ /opt/sge/util/arch -mt
/opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
++ MANTYPE=man
++ DRMAA_LIBRARY_PATH=/opt/sge/lib//libdrmaa.so
++ SGE_CELL=default
++ export SGE_CELL
++ SGE_CLUSTER_NAME=p6444
++ export SGE_CLUSTER_NAME
++ unset SGE_QMASTER_PORT
++ unset SGE_EXECD_PORT
++ '[' -d /opt/sge/man ']'
+ source /opt/sge/default/common/settings.sh
++ SGE_ROOT=/opt/sge
++ export SGE_ROOT
++ '[' -x /opt/sge/util/arch ']'
+++ /opt/sge/util/arch
/opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
++ SGE_ARCH=lx-amd64
++ export SGE_ARCH
+++ /opt/sge/util/arch -m
/opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
++ DEFAULTMANPATH=/usr/share/man:/usr/local/share/man
+++ /opt/sge/util/arch -mt
/opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
++ MANTYPE=man
++ DRMAA_LIBRARY_PATH=/opt/sge/lib//libdrmaa.so
++ SGE_CELL=default
++ export SGE_CELL
++ SGE_CLUSTER_NAME=p6444
++ export SGE_CLUSTER_NAME
++ unset SGE_QMASTER_PORT
++ unset SGE_EXECD_PORT
++ '[' -d /opt/sge/man ']'
++ '[' '' = '' ']'
++ MANPATH=/usr/share/man:/usr/local/share/man
++ MANPATH=/opt/sge/man:/usr/share/man:/usr/local/share/man
++ export MANPATH
++ PATH=/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
++ export PATH
++ '[' -d /opt/sge/lib/lx-amd64 ']'
++ case $SGE_ARCH in
+++ /opt/sge/util/arch -lib
/opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
++ shlib_path_name=LD_LIBRARY_PATH
+++ eval echo '$LD_LIBRARY_PATH'
++++ echo
++ old_value=
++ '[' x = x ']'
++ eval LD_LIBRARY_PATH=/opt/sge/lib/lx-amd64
+++ LD_LIBRARY_PATH=/opt/sge/lib/lx-amd64
++ export LD_LIBRARY_PATH
++ unset shlib_path_name old_value
++ unset DEFAULTMANPATH MANTYPE
+ qhost -q
+ qconf -as ubumaster
ubumaster added to submit host list
```
- `systemctl status` tells me:
```
● sgemaster.service - Grid Engine qmaster
     Loaded: loaded (/etc/systemd/system/sgemaster.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-05-18 18:59:34 UTC; 10min ago
   Main PID: 7327 (sge_qmaster)
      Tasks: 13 (limit: 2200)
     Memory: 2.8M
        CPU: 430ms
     CGroup: /system.slice/sgemaster.service
             └─7327 /opt/sge/bin/lx-amd64/sge_qmaster

May 18 18:59:32 ubumaster systemd[1]: Starting Grid Engine qmaster...
May 18 18:59:32 ubumaster sgemaster[7232]: /opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
May 18 18:59:32 ubumaster sgemaster[7250]: /opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
May 18 18:59:32 ubumaster sgemaster[7275]: /opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
May 18 18:59:32 ubumaster sgemaster[7294]: /opt/sge/util/arch: 1: /lib/x86_64-linux-gnu/libc.so.6: Permission denied
May 18 18:59:32 ubumaster sgemaster[7217]:    Starting Grid Engine qmaster
May 18 18:59:34 ubumaster systemd[1]: Started Grid Engine qmaster.
```

**Comment by daimh** [comment]
Thank you so much for the update! Truly appreciate the write up! I will modify it to remove this error message when I get a chance!

**Comment by Jerrythafast** [comment]
Thanks, that would be great! Keep it up :)
