### ISSUE TITLE
systemd templates do not match CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by chunk0tronic** [daimh/sge#24]
Hi, I built and installed sge on a Centos 7.6 system, to a non-default location - I changed the CMAKE_INSTALL_PREFIX.

When I went through the install_qmaster and install_execd steps, both services failed to properly start (I didn't notice at first because there was no error). I tracked this down to incorrect directory locations in the .service files. These are static, and do not reflect the modified CMAKE_INSTALL_PREFIX.

I fixed these paths manually and re-ran the install scripts, while skipping the overwrite of the .service files and got it to work. One improvement could also be to highlight the error in the install scripts when this occurs, I didn't realise there was an issue at the time I ran them.

**Comment by daimh** [comment]
Thanks a lot for reporting this issue! It is fixed and tested in the latest commit 'b6a216c'. Your help is acknowledged in the git log.

**Comment by chunk0tronic** [comment]
Nice, thanks for the fix!
