### ISSUE TITLE
How to increase the limit of number of open files for SGE jobs?

### ISSUE THREAD

**Issue by bayegy** [daimh/sge#26]
`echo "whoami && ulimit -n" | qsub -q queue10`

This is the command I used to get the limit of number of open files for SGE jobs on Ubuntu 16.04 system, and I always get 1024. 

I tried to add the following lines to the file /etc/security/limits.conf of master node and exec node:

> \* hard nofile 65536
> \* soft nofile 65536

and add the following line to the files /etc/pam.d/common-session,  /etc/pam.d/common-session-noninteractive of master node and exec node:

>session    required   pam_limits.so

and reboot SGE master node and exec node, but I still get 1024.

Is there a way to increase the limit of number of open files for SGE jobs?

Thanks!

**Comment by daimh** [comment]
Add a line like "LimitNOFILE=524288" to [Service] section in file '/etc/systemd/system/sgeexecd.service", and then run

systemctl daemon-reload
systemctl restart sgeexecd

Please keep us updated.
