### ISSUE TITLE
Use $SGE_CELL instead of default when installing startup scripts

### ISSUE THREAD

**Issue by jeffryr** [daimh/sge#30]
First a big thank-you for keeping this project alive!  We've been using this for over twenty years now starting with Sun Grid Engine, then Son of Grid Engine and now Some Grid Engine.  By convention we use the name of the project (first letter capitalized) as the cell name and the name of the project (all lowercase) as the name of the cluster.  There is a note in the systemd *.service.m4 files to modify the file if the cell isn't "default".  More often than not I forget to do this, go through the qmaster installation on a test machine and then remember it when qmaster fails to start.  The attached patch substitutes $SGE_CELL for default at installation time.  Tested on Rocky Linux 8.8, should work on any systemd/SysV init OS.
[sge_patch.txt](https://github.com/daimh/sge/files/13788495/sge_patch.txt)

**Comment by daimh** [comment]
Thanks for the patch file! It was added to commit '1de25e7'.

**Comment by daimh** [comment]
Thanks for the patch file! It was added to commit '1de25e7'.
