### ISSUE TITLE
undefined reference to `xdrmem_create', 'xdr_double'  in AlmaLinux 9.3

### ISSUE THREAD

**Issue by aoreshkin** [daimh/sge#32]
Hello,
I am trying to install SGE on AlmaLinux 9.3. 
Before installing SGE I've installed:
dnf install https://repo.almalinux.org/almalinux/9/CRB/x86_64/os/Packages/libtirpc-devel-1.3.3-2.el9.x86_64.rpm
dnf install cmake hwloc-devel libdb-devel motif-devel ncurses-devel openssl-devel pam-devel rsync systemd-devel wget
dnf group install "Development Tools"

As there are no many header files in /usr/include/rpc I've manually copied  them from /usr/include/tirpc/rpc
to /usr/include/rpc as follows:
cp rpc.h  /usr/include/rpc/
cp types.h  /usr/include/rpc/
cp xdr.h  /usr/include/rpc/
cp auth.h  /usr/include/rpc/
cp clnt.h  /usr/include/rpc/
cp rpc_msg.h  /usr/include/rpc/
cp auth_unix.h  /usr/include/rpc/
cp auth_des.h  /usr/include/rpc/
cp svc.h  /usr/include/rpc/
cp svc_auth.h  /usr/include/rpc/

Then I've performed the following steps:
1. git clone https://github.com/daimh/sge.git
2. cd sge
3. sh scripts/bootstrap.sh -no-java -no-jni -no-secure -spool-classic -no-remote -no-gui-inst
4. ./aimk -no-java -no-jni -no-secure -spool-classic -no-remote -no-gui-inst
Got such error:
...
cc -DSGE_ARCH_STRING=\"lx-amd64\" -O2 -Wstrict-prototypes -DLINUX -DLINUXAMD64 -DLINUXAMD64 -D_GNU_SOURCE -DGETHOSTBYNAME_R6 -DGETHOSTBYADDR_R8  -DTARGET_64BIT  -DSGE_PQS_API -DSPOOLING_classic  -DHAVE_HWLOC=1 -DNO_JNI -DCOMPILE_DC -D__SGE_COMPILE_WITH_GETTEXT__  -D__SGE_NO_USERMAPPING__ -I../common -I../libs -I../libs/uti -I../libs/juti -I../libs/gdi -I../libs/japi -I../libs/sgeobj -I../libs/cull -I../libs/comm -I../libs/comm/lists -I../libs/sched -I../libs/evc -I../libs/evm -I../libs/mir -I../daemons/common -I../daemons/qmaster -I../daemons/execd -I../clients/common -I. -o test_sge_object -L.  -Wl,--as-needed,-rpath,\$ORIGIN/../../lib/lx-amd64  test_sge_object.o libsgeobj.a libsgeobjd.a libcull.a libcomm.a libcommlists.a libuti.a  -luti -ldl  -lm -lpthread
/usr/bin/ld: libcull.a(pack.o): in function `packdouble':
pack.c:(.text+0x36c): undefined reference to `xdrmem_create'
/usr/bin/ld: pack.c:(.text+0x379): undefined reference to `xdr_double'
/usr/bin/ld: libcull.a(pack.o): in function `unpackdouble':
pack.c:(.text+0x7df): undefined reference to `xdrmem_create'
/usr/bin/ld: pack.c:(.text+0x7ea): undefined reference to `xdr_double'
collect2: error: ld returned 1 exit status
make: *** [../libs/sgeobj/Makefile:364: test_sge_object] Error 1
not done
On AlmaLinux 9.3 in glibc-2.34-83.el9_3.7.x86_64  in /lib64/libc.so.6
there are such modules:
nm /lib64/libc.so.6 | grep xdrmem_create
000000000018e8d0 t __GI_xdrmem_create
000000000018e8d0 T xdrmem_create@GLIBC_2.2.5

nm /lib64/libc.so.6 | grep xdr_double
0000000000183280 t __GI_xdr_double
0000000000183280 T xdr_double@GLIBC_2.2.5

But xdrmem_create, xdr_double are absent. 
I guess it is that may be the reason ?

I wonder how you manged to test SGE on AlmaLinux 9.3 ?
Could you help me how to workaround my problem ?

**Comment by daimh** [comment]
Can you please try the 'cmake' method?

My weekly automated tests are based on cmake. After a basic Linux OS is prepared, the same script on all Linux distros will call the commands in the file below to compile and install SGE.
https://github.com/daimh/sge/blob/master/tests/include/00-sge-install.sh

**Comment by aoreshkin** [comment]
I've run the script
https://github.com/daimh/sge/blob/master/tests/include/00-sge-install.sh and
SGE  have been installed successfully in /opt/sge on AlmaLinux 9.3.
It looks like old method of installing SGE on AlmaLinux 9.3 requires
corrections to work   successfully.
Or may be old method is not applicable at all ?
I would like to make rpm for SGE using sge.spec but I think sge.spec needs
to be corrected for using cmake ?
What is your opinion on this?
Thank you.



сб, 17 февр. 2024 г. в 03:31, daimh ***@***.***>:

**Comment by daimh** [comment]
I just tested the legacy aimk installation worked under Alma 9.3 too. After 'git clone', please 'dnf install csh', and then run 'make'. To get the exact 'aimk' commands, checkout 'compile.sh', which is generated with  'make'.

Please update when you get a chance, Thanks!

**Comment by aoreshkin** [comment]
I've managed to make rpm file for SGE  on AlmaLinux 9.3 using cmake.
spec file looks like this:

%build
cd sge
cmake -S . -B build
-DCMAKE_INSTALL_PREFIX=~/rpmbuild/BUILD/%{name}-%{version}/usr/sge-%{version}
cmake --build build -j
cmake --install build

%install
cp -a usr/sge-%{version} %{buildroot}/usr/

%files
/usr/sge-%{version}
%docdir /usr/sge-%{version}/man
%docdir /usr/sge-%{version}/doc

When I've tried to install rpm
rpm -ivh ~/rpmbuild/RPMS/x86_64/sge-8.1.10-1.x86_64.rpm
got
Error: Failed dependencies:
        /usr/bin/ruby is needed by sge-8.1.10-1.x86_64
        perl(FindBin) is needed by sge-8.1.10-1.x86_64
        perl(XML::Simple) is needed by sge-8.1.10-1.x86_64

I don't  want using /usr/bin/ruby.
As I guess I need to exclude some component  from CMakeLists.txt ?
Currently my  CMakeLists.txt  contains the lines:
...
add_compile_definitions(
        SGE_ARCH_STRING="lx-amd64"
        LINUX
        LINUXAMD64
        GETHOSTBYNAME_R6
        GETHOSTBYADDR_R8
        TARGET_64BIT
        SGE_PQS_API
        SPOOLING_dynamic
        SECURE
        HAVE_HWLOC=1
        NO_JNI
        NO_HADOOP
        NO_DRMAA4RUBY
        COMPILE_DC
        __SGE_COMPILE_WITH_GETTEXT__
        __SGE_NO_USERMAPPING__
)
...

Can I change SPOOLING_dynamic   to    spool classic ?
What type of spooling is supported in current release of SGE ?
What key word should I specify in CMakeLists.txt for example to exclude
some component which  using /usr/bin/ruby ?
Where can I learn what key words can be specified in  CMakeLists.txt ?
Thank you.







пн, 19 февр. 2024 г. в 23:39, daimh ***@***.***>:

**Comment by daimh** [comment]
Some Grid Engine supports the same spooling as before.

The ruby requirement is from your rpm spec file. Neither cmake nor the legacy aimk needs ruby.

If your RPM spec file works, feel free to send me a pull request. I will try to add it to the automated weekly test to benefit RHEL users.
