### ISSUE TITLE
missing files after installation

### ISSUE THREAD

**Issue by Suzy-Wong** [daimh/sge#34]
I have installed Some Grid Engine on Alma 9.3, using 3 cmake commands (recommended option). However, then proceeding to the "Quick test on one machine" stage, I find there is no bootstrap file, nor default/common/settings.sh

**Comment by daimh** [comment]
Thank you for the feedback!

I modified the README, as you actually don't need the bootstrap file, the default directory will be created after you run './install_qmaster"

https://github.com/daimh/sge/blob/master/tests/include/00-sge-install.sh is the automated weekly test script to install SGE on a virtual machine, FWIW.

**Comment by daimh** [comment]
Close
