### ISSUE TITLE
Info Request: SGE Implementations

### ISSUE THREAD

**Issue by ellestad** [daimh/sge#9]
Hi Some Grid Engine Maintainers,

I am a System Administrator at the University of California in San Francisco.

We run an HPC cluster based on the latest/last version of Son of Grid Engine.

https://wynton.ucsf.edu/hpc/

We've been surveying resources for scheduler options outside of Slurm and ran across your github project.

Our group had a couple questions about your SGE fork.

1) SystemD support.

"If they're running the sge_execd on the nodes via SystemD, that actually has some unintended consequences. In our version of SGE (and Altair's), you can run "service sgeexecd softstop" and that stops the currently running execd without killing the jobs on the node. That's handy if you need to restart the execd for some reason (which happens)."

2) We have run into a problem with resource complexes, particularly as they relate to GPUs. This bug forced us to use a less than desired workaround for GPU scheduling. Is this anything you have seen in your SGE cluster?

Described in this email thread from 2018:

http://gridengine.org/pipermail/users/2018-April/010116.html

More information here:

http://gridengine.org/pipermail/users/2018-April/010127.html

Thanks for any insight!

**Comment by daimh** [comment]
Thanks for the good idea, @Ondrej! Happy New Year!

Best,
Manhong
